"""add_approved_at

Revision ID: db55f5cbc6c6
Revises: 8a7755eb73f4
Create Date: 2026-06-03 09:18:12.111001

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db55f5cbc6c6"
down_revision: Union[str, Sequence[str], None] = "8a7755eb73f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
